import Link from 'next/link';
import { api } from '@/lib/api';
import PrintButton from '../PrintButton';

// Türkçe anlam sözlüğü
const meanings: Record<string, string> = {
  // A1
  'across': 'karşıya, boyunca',
  'actress': 'kadın oyuncu',
  'anyone': 'herhangi biri',
  'anything': 'herhangi bir şey',
  'around': 'etrafında, civarında',
  'arrive': 'varmak, ulaşmak',
  'band': 'grup, bant',
  'become': 'olmak, haline gelmek',
  'begin': 'başlamak',
  'below': 'aşağıda, altında',
  'bored': 'sıkılmış, canı sıkılan',
  'boring': 'sıkıcı',
  'carrot': 'havuç',
  'carry': 'taşımak',
  'coat': 'palto, ceket',
  'concert': 'konser',
  'cost': 'maliyet, fiyat; mal olmak',
  'could modal': 'yapabilirdi, -ebilirdi',
  'describe': 'tanımlamak, betimlemek',
  'dialogue': 'diyalog, konuşma',
  'discuss': 'tartışmak, görüşmek',
  'dish': 'tabak, yemek',
  'during': 'sırasında, süresince',
  'evening': 'akşam',
  'exercise': 'egzersiz, alıştırma',
  'fact': 'gerçek, olgu',
  'few': 'birkaç, az',
  'floor': 'zemin, kat',
  'food': 'yiyecek, gıda',
  'foot': 'ayak',
  'happen': 'olmak, meydana gelmek',
  'however': 'ancak, bununla birlikte',
  'introduce': 'tanıştırmak, sunmak',
  'late': 'geç',
  'lot': 'çok, bir sürü',
  'magazine': 'dergi',
  'meat': 'et',
  'meet': 'tanışmak, buluşmak',
  'meter': 'metre, sayaç',
  'midnight': 'gece yarısı',
  'next to': 'yanında, bitişiğinde',
  'opposite': 'karşı, zıt',
  'over': 'üzerinde, üstünde',
  'pepper': 'biber',
  'phrase': 'deyim, ifade',
  'quite': 'oldukça, epey',
  'quiet': 'sessiz, sakin',
  'river': 'nehir, ırmak',
  'situation': 'durum, konum',
  'soup': 'çorba',
  'spell': 'hecelemek',
  'spelling': 'yazım, imla',
  'statement': 'açıklama, ifade',
  'sweater': 'kazak',
  'theater': 'tiyatro',
  'thirsty': 'susamış',
  'through': 'boyunca, aracılığıyla',
  'vacation': 'tatil',
  'waiter': 'garson',

  // A2
  'ability': 'yetenek, beceri',
  'able': 'yapabilir, muktedir',
  'according to': 'göre',
  'advantage': 'avantaj, üstünlük',
  'affect': 'etkilemek',
  'against': 'karşı, aleyhine',
  'airline': 'havayolu',
  'almost': 'neredeyse, hemen hemen',
  'although': 'rağmen, her ne kadar',
  'among': 'arasında',
  'ancient': 'antik, eski',
  'ankle': 'ayak bileği',
  'annoy': 'kızdırmak, rahatsız etmek',
  'annoyed': 'sinirli, kızgın',
  'annoying': 'sinir bozucu, can sıkıcı',
  'anymore': 'artık',
  'appear': 'görünmek, ortaya çıkmak',
  'appearance': 'görünüş, dış görünüm',
  'arrange': 'düzenlemek, ayarlamak',
  'arrangement': 'düzenleme, anlaşma',
  'asleep': 'uykuda',
  'attend': 'katılmak',
  'attention': 'dikkat, ilgi',
  'audience': 'seyirci, izleyici',
  'avoid': 'kaçınmak, sakınmak',
  'awful': 'berbat, korkunç',
  'bean': 'fasulye',
  'behave': 'davranmak',
  'behavior': 'davranış',
  'belong': 'ait olmak',
  'belt': 'kemer',
  'blow': 'esmek, üflemek',
  'brilliant': 'parlak, harika',
  'campus': 'kampüs, yerleşke',
  'carpet': 'halı',
  'cause': 'sebep, neden; neden olmak',
  'celebrate': 'kutlamak',
  'celebrity': 'ünlü kişi',
  'century': 'yüzyıl',
  'certain': 'kesin, belirli',
  'certainly': 'kesinlikle, elbette',
  'charity': 'hayır kurumu, yardım',
  'clearly': 'açıkça, net olarak',
  'clerk': 'katip, memur',
  'climate': 'iklim',
  'closet': 'dolap, gardırop',
  'coast': 'kıyı, sahil',
  'compete': 'yarışmak, rekabet etmek',
  'complain': 'şikayet etmek',
  'consider': 'düşünmek, dikkate almak',
  'context': 'bağlam',
  'continent': 'kıta',
  'correctly': 'doğru bir şekilde',
  'crowd': 'kalabalık',
  'cross': 'geçmek, karşıdan karşıya',
  'crowded': 'kalabalık',
  'department': 'bölüm, departman',
  'depend': 'bağlı olmak, güvenmek',
  'diary': 'günlük',
  'disappear': 'kaybolmak, ortadan kalkmak',
  'disaster': 'felaket, afet',
  'disease': 'hastalık',
  'distance': 'mesafe, uzaklık',
  'downstairs': 'alt kata, alt katta',
  'downtown': 'şehir merkezi',
  'either': 'her iki, ya da',
  'employ': 'istihdam etmek, çalıştırmak',
  'employee': 'çalışan, işçi',
  'employer': 'işveren',
  'enormous': 'devasa, muazzam',
  'essay': 'deneme, makale',
  'evidence': 'kanıt, delil',
  'exact': 'kesin, tam',
  'exactly': 'tam olarak, aynen',
  'expression': 'ifade, deyim',
  'express': 'ifade etmek, belirtmek',
  'extremely': 'son derece, aşırı',
  'fail': 'başarısız olmak',
  'fair': 'adil, hakkaniyetli',
  'fever': 'ateş (hastalık)',
  'flu': 'grip',
  'foreign': 'yabancı',
  'fork': 'çatal',
  'formal': 'resmi',
  'fortunately': 'neyse ki, şans eseri',
  'grass': 'çimen, ot',
  'greet': 'selamlamak, karşılamak',
  'ground': 'zemin, yer',
  'grocery': 'bakkal, market',
  'habit': 'alışkanlık',
  'hall': 'salon, hol',
  'headache': 'baş ağrısı',
  'hill': 'tepe',
  'ill': 'hasta, rahatsız',
  'illness': 'hastalık',
  'immediately': 'hemen, derhal',
  'included': 'dahil, içerilmiş',
  'including': 'dahil olmak üzere',
  'independent': 'bağımsız',
  'informal': 'gayri resmi, gündelik',
  'injury': 'yaralanma, sakatlanma',
  'insect': 'böcek',
  'instruction': 'talimat, yönerge',
  'instructor': 'eğitmen, öğretmen',
  'invent': 'icat etmek',
  'invention': 'icat, buluş',
  'involve': 'içermek, dahil etmek',
  'jam': 'reçel; tıkanıklık',
  'kilometer': 'kilometre',
  'knee': 'diz',
  'later': 'sonra, daha sonra',
  'least': 'en az',
  'lecture': 'ders, konferans',
  'lend': 'ödünç vermek',
  'less': 'daha az',
  'likely': 'muhtemel, olası',
  'manner': 'tarz, davranış biçimi',
  'mayor': 'belediye başkanı',
  'nearly': 'neredeyse, hemen hemen',
  'necessary': 'gerekli, zorunlu',
  'noisy': 'gürültülü',
  'noise': 'gürültü',
  'nowhere': 'hiçbir yer',
  'onto': 'üzerine',
  'opportunity': 'fırsat',
  'ordinary': 'sıradan, olağan',
  'ourselves': 'kendimiz',
  'oven': 'fırın',
  'particular': 'belirli, özel',
  'perform': 'yapmak, sahnelemek',
  'perhaps': 'belki, olabilir',
  'plate': 'tabak',
  'pleased': 'memnun, hoşnut',
  'pollution': 'kirlilik',
  'possession': 'mülk, sahiplik',
  'prevent': 'önlemek, engellemek',
  'purpose': 'amaç, maksat',
  'quietly': 'sessizce, sakin bir şekilde',
  'railroad': 'demiryolu',
  'rather': 'oldukça; tercihan',
  'recently': 'son zamanlarda',
  'recent': 'son, yakın zamandaki',
  'reception': 'resepsiyon, kabul',
  'recipe': 'tarif, yemek tarifi',
  'recognize': 'tanımak, fark etmek',
  'recommend': 'tavsiye etmek, önermek',
  'refer': 'atıfta bulunmak, yönlendirmek',
  'refrigerator': 'buzdolabı',
  'rude': 'kaba, saygısız',
  'sailing': 'yelken, yelkencilik',
  'seem': 'görünmek, gibi görünmek',
  'serve': 'servis yapmak, hizmet etmek',
  'sheet': 'çarşaf, yaprak',
  'several': 'birkaç, çeşitli',
  'shout': 'bağırmak',
  'site': 'alan, yer, site',
  'ski': 'kayak yapmak',
  'skiing': 'kayak',
  'somewhere': 'bir yerde, bir yere',
  'spoon': 'kaşık',
  'stair': 'merdiven basamağı',
  'stamp': 'pul, damga',
  'stove': 'soba, ocak',
  'stone': 'taş',
  'storm': 'fırtına',
  'subway': 'metro',
  'themselves': 'kendileri',
  'thick': 'kalın, yoğun',
  'suppose': 'sanmak, farz etmek',
  'thin': 'ince, zayıf',
  'thought': 'düşünce, fikir',
  'tie': 'bağlamak; kravat',
  'throw': 'fırlatmak, atmak',
  'toward': 'doğru, yönünde',
  'towel': 'havlu',
  'transportation': 'ulaşım, taşımacılık',
  'typical': 'tipik, karakteristik',
  'underground': 'yeraltı',
  'unit': 'birim, ünite',
  'united': 'birleşik',
  'upstairs': 'üst kata, üst katta',
  'valley': 'vadi',
  'variety': 'çeşitlilik',
  'whose': 'kimin',
  'worried': 'endişeli, kaygılı',
  'wood': 'ahşap, odun',
  'wooden': 'ahşap, tahtadan',
  'advertisement': 'reklam, ilan',

  // B1
  'ahead': 'ileride, önde',
  'admire': 'hayran olmak, beğenmek',
  'admit': 'kabul etmek, itiraf etmek',
  'advise': 'tavsiye etmek',
  'afford': 'karşılayabilmek (maddi)',
  'amazed': 'şaşkın, hayrete düşmüş',
  'ambition': 'hırs, tutku',
  'announce': 'duyurmak, ilan etmek',
  'appreciate': 'takdir etmek, değer vermek',
  'appointment': 'randevu',
  'approximately': 'yaklaşık olarak',
  'arrest': 'tutuklama; tutuklamak',
  'arrival': 'varış, geliş',
  'assignment': 'ödev, görev',
  'assist': 'yardım etmek',
  'attitude': 'tutum, tavır',
  'attract': 'çekmek, cezbetmek',
  'attraction': 'cazibe, ilgi çekici yer',
  'award': 'ödül; ödüllendirmek',
  'aware': 'farkında',
  'backward': 'geriye doğru',
  'basis': 'temel, esas',
  'belief': 'inanç, kanı',
  'bend': 'eğilmek, bükmek',
  'benefit': 'fayda, yarar',
  'branch': 'dal, şube',
  'breath': 'nefes',
  'breathe': 'nefes almak',
  'breathing': 'soluk alma, nefes',
  'bride': 'gelin',
  'bury': 'gömmek',
  'candidate': 'aday',
  'careless': 'dikkatsiz, özensiz',
  'ceiling': 'tavan',
  'celebration': 'kutlama',
  'chapter': 'bölüm (kitap)',
  'cheerful': 'neşeli, şen',
  'childhood': 'çocukluk',
  'clause': 'cümlecik, madde',
  'clever': 'zeki, akıllı',
  'clue': 'ipucu',
  'coal': 'kömür',
  'combine': 'birleştirmek, kombine etmek',
  'competitor': 'rakip',
  'complaint': 'şikayet',
  'concentrate': 'yoğunlaşmak, konsantre olmak',
  'conclude': 'sonuçlandırmak',
  'conclusion': 'sonuç, vardığı karar',
  'confident': 'özgüvenli, emin',
  'confuse': 'karıştırmak, şaşırtmak',
  'consequence': 'sonuç (olumsuz)',
  'consist': 'oluşmak, meydana gelmek',
  'consume': 'tüketmek',
  'consumer': 'tüketici',
  'continuous': 'sürekli, kesintisiz',
  'convenient': 'uygun, elverişli',
  'convince': 'ikna etmek',
  'cotton': 'pamuk',
  'countryside': 'kırsal alan, taşra',
  'court': 'mahkeme; kort',
  'cover': 'kaplamak, örtmek',
  'covered': 'kaplı, örtülü',
  'cruel': 'zalim, acımasız',
  'cupboard': 'dolap, mutfak dolabı',
  'curtain': 'perde',
  'decade': 'on yıl',
  'define': 'tanımlamak',
  'definite': 'kesin, belirli',
  'definition': 'tanım',
  'departure': 'kalkış, ayrılış',
  'despite': 'rağmen',
  'destination': 'varış noktası, hedef',
  'determine': 'belirlemek, saptamak',
  'determined': 'kararlı, azimli',
  'disappointed': 'hayal kırıklığına uğramış',
  'disappointing': 'hayal kırıklığı yaratan',
  'disadvantage': 'dezavantaj, sakınca',
  'dislike': 'hoşlanmamak, sevmemek',
  'district': 'ilçe, bölge, semt',
  'doubt': 'şüphe; şüphelenmek',
  'duty': 'görev, vazife',
  'dust': 'toz',
  'due': 'vadesi gelen; nedeniyle',
  'drum': 'davul',
  'effective': 'etkili, verimli',
  'embarrassed': 'utanmış, mahcup',
  'embarrassing': 'utandırıcı, mahcup edici',
  'encourage': 'cesaretlendirmek, teşvik etmek',
  'engaged': 'nişanlı; meşgul',
  'equally': 'eşit olarak',
  'essential': 'temel, zorunlu',
  'eventually': 'sonunda, en sonunda',
  'examine': 'incelemek, muayene etmek',
  'exhibition': 'sergi',
  'fairly': 'oldukça, adil bir şekilde',
  'familiar': 'tanıdık, aşina',
  'fancy': 'süslü, lüks; istemek',
  'far': 'uzak; çok',
  'fascinating': 'büyüleyici, harika',
  'fasten': 'bağlamak, tutturmak',
  'fashionable': 'modaya uygun, şık',
  'fence': 'çit, parmaklık',
  'flour': 'un',
  'flood': 'sel, taşkın',
  'flow': 'akmak, akış',
  'folk': 'halk, insanlar',
  'frequently': 'sık sık',
  'frighten': 'korkutmak',
  'fur': 'kürk',
  'further': 'daha ileri, daha fazla',
  'generous': 'cömert, eli açık',
  'glad': 'memnun, mutlu',
  'grain': 'tahıl, tane',
  'grateful': 'minnettar, müteşekkir',
  'imaginary': 'hayali, düşsel',
  'immediate': 'acil, ani, hemen',
  'impact': 'etki, darbe',
  'importance': 'önem',
  'impression': 'izlenim, intiba',
  'impressive': 'etkileyici, görkemli',
  'indirect': 'dolaylı',
  'indicate': 'göstermek, belirtmek',
  'injure': 'yaralamak, sakatlamak',
  'injured': 'yaralı, sakatlanmış',
  'intend': 'niyet etmek, planlamak',
  'intention': 'niyet, amaç',
  'journal': 'dergi, gazete; günlük',
  'lack': 'eksiklik, yokluk',
  'leaf': 'yaprak',
  'leather': 'deri',
  'leisure': 'boş vakit, dinlenme',
  'mad': 'deli, çılgın; kızgın',
  'mainly': 'esas olarak, başlıca',
  'meanwhile': 'bu arada, bu esnada',
  'mixture': 'karışım',
  'mud': 'çamur',
  'mystery': 'gizem, sır',
  'nail': 'çivi; tırnak',
  'narrative': 'anlatı, hikaye',
  'neat': 'düzenli, temiz',
  'necessarily': 'zorunlu olarak',
  'need': 'ihtiyaç duymak; gerek',
  'needle': 'iğne',
  'neither': 'hiçbiri, ne ... ne de',
  'net': 'ağ, file',
  'nor': 'ne de',
  'northern': 'kuzey, kuzeye ait',
  'obviously': 'açıkça, belli ki',
  'obvious': 'açık, bariz',
  'occasion': 'durum, vesile, fırsat',
  'overseas': 'denizaşırı, yurt dışında',
  'occur': 'meydana gelmek, olmak',
  'pack': 'paketlemek; paket',
  'outdoor': 'açık hava, dış mekan',
  'outdoors': 'dışarıda, açık havada',
  'painful': 'acı veren, ağrılı',
  'pale': 'solgun, soluk',
  'pan': 'tava',
  'participate': 'katılmak',
  'particularly': 'özellikle',
  'pleasant': 'hoş, keyifli',
  'pleasure': 'zevk, memnuniyet',
  'plenty': 'bol, çok',
  'poem': 'şiir',
  'poet': 'şair',
  'poisonous': 'zehirli',
  'poison': 'zehir; zehirlemek',
  'possibly': 'belki, muhtemelen',
  'poverty': 'yoksulluk, fakirlik',
  'pot': 'tencere, çömlek',
  'presentation': 'sunum',
  'prediction': 'tahmin, öngörü',
  'pretend': 'numarasını yapmak',
  'prisoner': 'mahkum, tutuklu',
  'proper': 'uygun, doğru',
  'properly': 'düzgün bir şekilde',
  'property': 'mülk, mal; özellik',
  'qualified': 'nitelikli, yetkin',
  'qualify': 'hak kazanmak, yeterliliğini almak',
  'quotation': 'alıntı',
  'reliable': 'güvenilir',
  'represent': 'temsil etmek',
  'remind': 'hatırlatmak',
  'revise': 'gözden geçirmek, tekrar etmek',
  'roll': 'yuvarla(n)mak; rulo',
  'rope': 'ip, halat',
  'rough': 'kaba, pürüzlü; sert',
  'sail': 'yelken açmak; yelken',
  'sailor': 'denizci, gemici',
  'sand': 'kum',
  'sculpture': 'heykel',
  'servant': 'hizmetçi',
  'shelf': 'raf',
  'sight': 'görüş, manzara',
  'shell': 'kabuk, mermi',
  'silly': 'aptalca, saçma',
  'similarity': 'benzerlik',
  'similarly': 'benzer şekilde',
  'slightly': 'biraz, hafifçe',
  'slice': 'dilim; dilimlemek',
  'slave': 'köle',
  'sink': 'batmak; lavabo',
  'since': 'beri; çünkü',
  'simply': 'basitçe, sadece',
  'soil': 'toprak',
  'spoken': 'sözlü, konuşulan',
  'substance': 'madde',
  'sudden': 'ani, beklenmedik',
  'suit': 'takım elbise; uymak',
  'suitable': 'uygun, elverişli',
  'surely': 'kesinlikle, elbette',
  'surface': 'yüzey',
  'symptom': 'belirti, semptom',
  'tail': 'kuyruk',
  'tend': 'eğiliminde olmak',
  'therefore': 'bu yüzden, dolayısıyla',
  'though': 'rağmen, yine de',
  'throughout': 'boyunca, her tarafında',
  'tight': 'dar, sıkı',
  'transport': 'taşımak, nakletmek',
  'treat': 'davranmak; tedavi etmek',
  'treatment': 'tedavi, muamele',
  'trick': 'numara, hile',
  'underwear': 'iç çamaşırı',
  'unfair': 'haksız, adaletsiz',
  'union': 'birlik, sendika',
  'unless': 'olmadıkça, -medikçe',
  'unlike': 'aksine, farklı olarak',
  'unlikely': 'olası değil',
  'unnecessary': 'gereksiz',
  'unpleasant': 'nahoş, tatsız',
  'upon': 'üzerine, üzerinde',
  'upset': 'üzgün, bozulmuş',
  'various': 'çeşitli, muhtelif',
  'violent': 'şiddetli, saldırgan',
  'weigh': 'tartmak',
  'whatever': 'her ne, ne olursa olsun',
  'whenever': 'her ne zaman, ne zaman',
  'whether': 'olup olmadığını, -ip -mediğini',
  'within': 'içinde, dahilinde',
  'wing': 'kanat',
  'whole': 'bütün, tam',
  'while': 'iken, sırasında',
  'wool': 'yün',
  'specifically': 'özellikle, spesifik olarak',
  'southern': 'güney, güneye ait',
  'spring': 'ilkbahar; yay; fışkırmak',
  'statue': 'heykel',
  'stick': 'yapışmak; çubuk, sopa',
  'strength': 'güç, kuvvet',
  'suffer': 'acı çekmek, sıkıntı çekmek',
  'worldwide': 'dünya çapında',
  'written': 'yazılı',
  'worry': 'endişelenmek; endişe',
  'youth': 'gençlik',
  'young': 'genç',
  'mild': 'hafif, ılıman, yumuşak',
  'mess': 'dağınıklık, karmaşa',
  'western': 'batı, batıya ait',
  'toe': 'ayak parmağı',
  'tire': 'lastik',

  // B2
  'abandon': 'terk etmek, vazgeçmek',
  'accompany': 'eşlik etmek',
  'accurate': 'doğru, kesin',
  'accuse': 'suçlamak, itham etmek',
  'acknowledge': 'kabul etmek, onaylamak',
  'acquire': 'edinmek, kazanmak',
  'afterward': 'sonradan, daha sonra',
  'aircraft': 'uçak, hava aracı',
  'alter': 'değiştirmek',
  'amount': 'miktar; ulaşmak',
  'angle': 'açı',
  'anniversary': 'yıl dönümü',
  'apparent': 'görünürdeki, besbelli',
  'apparently': 'görünüşe göre, anlaşılan',
  'appeal': 'çekicilik; başvurmak',
  'approach': 'yaklaşım; yaklaşmak',
  'appropriate': 'uygun, yerinde',
  'arise': 'ortaya çıkmak, doğmak',
  'artificial': 'yapay, suni',
  'ashamed': 'utanmış, mahcup',
  'aside': 'bir yana, bir kenara',
  'aspect': 'yön, boyut',
  'assess': 'değerlendirmek',
  'assessment': 'değerlendirme',
  'associate': 'ilişkilendirmek, bağdaştırmak',
  'associated': 'ilişkili, bağlantılı',
  'association': 'dernek, kuruluş; çağrışım',
  'assume': 'varsaymak, kabul etmek',
  'attempt': 'deneme, girişim; denemek',
  'attorney': 'avukat',
  'bent': 'bükülmüş, eğilmiş',
  'beyond': 'ötesinde, ötede',
  'abroad': 'yurt dışında',
  'affair': 'mesele, iş; ilişki',
  'bitter': 'acı, kırgın',
  'blame': 'suçlamak; suç',
  'breast': 'göğüs, meme',
  'broad': 'geniş, enli',
  'bunch': 'demet, grup',
  'bush': 'çalı, çalılık',
  'capable': 'yetenekli, muktedir',
  'circumstance': 'durum, koşul',
  'cite': 'alıntı yapmak, kaynak göstermek',
  'collapse': 'çökmek; çöküş',
  'commitment': 'bağlılık, taahhüt',
  'committee': 'komite, kurul',
  'conduct': 'yürütmek; davranış',
  'confidence': 'güven, özgüven',
  'concentration': 'yoğunlaşma, konsantrasyon',
  'conscious': 'bilinçli, farkında',
  'constant': 'sürekli, sabit',
  'consistent': 'tutarlı, istikrarlı',
  'construct': 'inşa etmek, kurmak',
  'convinced': 'ikna olmuş, emin',
  'council': 'meclis, konsey',
  'courage': 'cesaret, yüreklilik',
  'criterion': 'ölçüt, kriter',
  'crucial': 'çok önemli, kritik',
  'cure': 'tedavi etmek; tedavi',
  'debt': 'borç',
  'declare': 'ilan etmek, beyan etmek',
  'deliberate': 'kasıtlı, bilinçli',
  'deliberately': 'kasıtlı olarak, bilerek',
  'demonstrate': 'göstermek, kanıtlamak',
  'desire': 'arzu, istek; arzulamak',
  'desperate': 'çaresiz, umutsuz',
  'dishonest': 'dürüst olmayan, namussuz',
  'distribute': 'dağıtmak',
  'distribution': 'dağıtım',
  'divide': 'bölmek, ayırmak',
  'division': 'bölüm, bölünme',
  'downward': 'aşağı doğru',
  'dozen': 'düzine',
  'elsewhere': 'başka yerde',
  'elect': 'seçmek (oy ile)',
  'emphasize': 'vurgulamak',
  'encounter': 'karşılaşmak; karşılaşma',
  'engage': 'meşgul etmek, dahil etmek',
  'enhance': 'geliştirmek, arttırmak',
  'ensure': 'sağlamak, garanti etmek',
  'establish': 'kurmak, tesis etmek',
  'estimate': 'tahmin etmek; tahmin',
  'estate': 'emlak, mülk',
  'evaluate': 'değerlendirmek',
  'examination': 'sınav; muayene',
  'executive': 'yönetici; yönetimle ilgili',
  'excuse': 'mazeret; affetmek',
  'exhibit': 'sergilemek; sergi',
  'existence': 'var oluş, varlık',
  'facility': 'tesis, olanak',
  'extraordinary': 'olağanüstü, sıra dışı',
  'extent': 'boyut, derece, ölçüde',
  'expose': 'açığa çıkarmak, maruz bırakmak',
  'extend': 'uzatmak, genişletmek',
  'exploration': 'keşif, araştırma',
  'expense': 'masraf, gider',
  'expectation': 'beklenti',
  'faith': 'inanç, güven',
  'fellow': 'arkadaş; aynı gruptaki',
  'frequency': 'sıklık, frekans',
  'fundamental': 'temel, esas',
  'furthermore': 'ayrıca, üstelik',
  'gain': 'kazanmak, elde etmek',
  'govern': 'yönetmek, hükmetmek',
  'governor': 'vali, yönetici',
  'gradually': 'yavaş yavaş, giderek',
  'harmful': 'zararlı',
  'heaven': 'cennet, gökyüzü',
  'heel': 'topuk',
  'hesitate': 'tereddüt etmek, çekinmek',
  'hollow': 'içi boş, oyuk',
  'household': 'hane, ev halkı',
  'housing': 'konut, barınma',
  'imagination': 'hayal gücü',
  'impatient': 'sabırsız',
  'imply': 'ima etmek, kastetmek',
  'impose': 'dayatmak, yüklemek',
  'impress': 'etkilemek',
  'impressed': 'etkilenmiş',
  'incident': 'olay, vaka',
  'initiative': 'girişim, inisiyatif',
  'inquiry': 'soruşturma, araştırma',
  'insight': 'içgörü, kavrayış',
  'insist': 'ısrar etmek',
  'inspire': 'ilham vermek, esinlendirmek',
  'instance': 'örnek, durum',
  'intended': 'amaçlanan, kasıtlı',
  'intense': 'yoğun, şiddetli',
  'interpret': 'yorumlamak, çeviri yapmak',
  'interrupt': 'sözünü kesmek, ara vermek',
  'labor': 'emek, işçilik',
  'loose': 'gevşek, bol',
  'melt': 'erimek, eritmek',
  'narrow': 'dar; daraltmak',
  'nerve': 'sinir',
  'numerous': 'çok sayıda',
  'obligation': 'yükümlülük, zorunluluk',
  'observation': 'gözlem',
  'observe': 'gözlemlemek, izlemek',
  'obtain': 'elde etmek, edinmek',
  'occasionally': 'ara sıra, zaman zaman',
  'offend': 'gücendirmek, kırmak',
  'offense': 'suç; gücenme',
  'offensive': 'saldırgan, kırıcı',
  'opponent': 'rakip, muhalif',
  'oppose': 'karşı çıkmak',
  'opposed': 'karşı, muhalif',
  'opposition': 'muhalefet, karşıtlık',
  'otherwise': 'aksi halde, yoksa',
  'outcome': 'sonuç',
  'overall': 'genel, toplu',
  'pace': 'hız, tempo; adım atmak',
  'permit': 'izin vermek; izin belgesi',
  'pitch': 'saha; perde (ses)',
  'plot': 'olay örgüsü; arsa; plan',
  'pose': 'poz vermek; teşkil etmek',
  'possess': 'sahip olmak',
  'praise': 'övmek; övgü',
  'preparation': 'hazırlık',
  'presence': 'varlık, mevcudiyet',
  'preserve': 'korumak, muhafaza etmek',
  'principal': 'müdür; başlıca',
  'principle': 'ilke, prensip',
  'prospect': 'olasılık, beklenti',
  'pursue': 'peşinden gitmek, takip etmek',
  'rapid': 'hızlı, çabuk',
  'rapidly': 'hızla, süratle',
  'recover': 'iyileşmek, kurtarmak',
  'wrap': 'sarmak, paketlemek',
  'wound': 'yara; yaralamak',
  'witness': 'tanık; şahit olmak',
  'wise': 'bilge, akıllı',
  'wire': 'tel, kablo',
  'willing': 'istekli, gönüllü',
  'widely': 'yaygın olarak, geniş çapta',
  'wildlife': 'yaban hayatı',
  'whom': 'kimi, kime',
  'wherever': 'nereye, her nerede',
  'whereas': 'oysa, halbuki',
  'wealthy': 'zengin, varlıklı',
  'wealth': 'servet, zenginlik',
  'violence': 'şiddet',
  'venue': 'mekan, yer',
  'vast': 'çok geniş, engin',
  'vary': 'farklılık göstermek, değişmek',
  'urge': 'teşvik etmek, zorlamak; dürtü',
  'upward': 'yukarı doğru',
  'urban': 'kentsel, şehre ait',
  'unconscious': 'bilinçsiz, baygın',
  'threat': 'tehdit',
  'temporary': 'geçici',
  'tale': 'masal, hikaye',
  'sweep': 'süpürmek',
  'swear': 'yemin etmek; küfretmek',
  'surround': 'çevrelemek, kuşatmak',
  'surrounding': 'çevredeki, etraftaki',
  'stretch': 'germek, uzatmak; esneme',
  'stiff': 'sert, katı',
  'sticky': 'yapışkan',
  'stare': 'dikkatle bakmak, gözünü dikmek',
  'steady': 'sabit, istikrarlı',
  'split': 'bölmek, ayırmak',
  'species': 'tür (biyoloji)',
  'somewhat': 'bir miktar, biraz',
  'slope': 'eğim, yamaç',
  'slight': 'hafif, önemsiz',
  'significant': 'önemli, anlamlı',
  'sincere': 'samimi, içten',
  'shallow': 'sığ, yüzeysel',
  'severe': 'şiddetli, ciddi',
  'sequence': 'sıra, dizi',
  'sense': 'duyu; his; anlam',
  'seek': 'aramak, çabalamak',
  'rural': 'kırsal',
  'rubber': 'kauçuk, lastik',
  'rub': 'ovmak, sürtmek',
  'relevant': 'ilgili, alakalı',
  'relief': 'rahatlama, ferahlama',
  'rely': 'güvenmek, bel bağlamak',
  'remark': 'yorum, açıklama; belirtmek',
  'representative': 'temsilci; temsili',
  'relatively': 'nispeten, görece',
  'regret': 'pişmanlık; pişman olmak',
  'publication': 'yayın, yayımlama',
  'proposal': 'teklif, öneri',
  'nevertheless': 'yine de, buna rağmen',
  'nightmare': 'kabus',
  'mysterious': 'gizemli, esrarengiz',
  'institution': 'kurum, kuruluş',
  'institute': 'enstitü, kurum',
  'humorous': 'komik, esprili',
  'harm': 'zarar; zarar vermek',
  'genre': 'tür (edebiyat/müzik)',
  'forward': 'ileri; ileriye doğru',
  'fortune': 'servet; talih, şans',
};

export default async function PdfUnknownPage() {
  const unknownWords = await api.getUnknownWords();

  // Group by level
  const grouped: Record<string, { word: string; type: string; meaning: string }[]> = {};

  unknownWords.forEach(w => {
    const wordStr = typeof w.word === 'string' ? w.word.trim() : '';
    if (!wordStr || !/^[a-zA-Z\-\s']+$/.test(wordStr)) return;

    let level = typeof w.level === 'string' ? w.level.trim() : 'Unknown';
    if (level === '') level = 'Unknown';

    if (!grouped[level]) grouped[level] = [];
    grouped[level].push({
      word: wordStr,
      type: w.type || '',
      meaning: meanings[wordStr.toLowerCase()] || '',
    });
  });

  // Sort levels: A1, A2, B1, B2, C1, C2, Unknown
  const levelOrder = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'Unknown'];
  const sortedLevels = Object.keys(grouped).sort((a, b) => {
    const ia = levelOrder.indexOf(a);
    const ib = levelOrder.indexOf(b);
    return (ia === -1 ? 999 : ia) - (ib === -1 ? 999 : ib);
  });

  // Sort words alphabetically within each level
  sortedLevels.forEach(level => {
    grouped[level].sort((a, b) => a.word.localeCompare(b.word));
  });

  const totalWords = Object.values(grouped).reduce((sum, arr) => sum + arr.length, 0);

  return (
    <main className="bg-white text-black font-sans print:text-[11px]" style={{ colorScheme: 'light' }}>
      {/* Screen-only navigation */}
      <div className="p-4 border-b border-gray-200 flex justify-between items-center print:hidden">
        <h1 className="text-lg font-bold">Unknown Words ({totalWords})</h1>
        <div className="flex gap-3">
          <Link href="/pdf" className="text-sm text-gray-500 hover:text-black transition-colors">
            ← PDF Sayfası
          </Link>
          <PrintButton />
        </div>
      </div>

      {/* Printable content */}
      <div className="px-6 py-4 print:px-2 print:py-0">
        {sortedLevels.map(level => (
          <div key={level} className="mb-4 print:mb-2 break-inside-avoid-page">
            {/* Level header */}
            <h2 className="text-base font-bold border-b-2 border-black pb-1 mb-2 print:text-sm print:mb-1 print:pb-0.5 uppercase tracking-wide">
              Level {level}
              <span className="font-normal text-gray-500 text-xs ml-2 normal-case tracking-normal">
                ({grouped[level].length} kelime)
              </span>
            </h2>

            {/* Words in compact multi-column layout */}
            <div className="columns-2 sm:columns-3 md:columns-4 print:columns-4 gap-x-4 text-[12px] print:text-[10px] leading-tight">
              {grouped[level].map((item, i) => (
                <div key={`${level}-${i}`} className="break-inside-avoid py-[1px] flex justify-between border-b border-gray-100 print:border-gray-200">
                  <span className="font-medium text-black">{item.word}</span>
                  <span className="text-gray-400 ml-1 text-[10px] print:text-[9px] italic shrink-0">
                    {item.meaning || '—'}
                  </span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
